
version: '3.4'

services:
  megara:
    image: megara
    build:
      context: .
      dockerfile: megara/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
